dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
dataSource.user=${DB_USER}
dataSource.password=${DB_PASSWORD}
dataSource.databaseName=${DB_NAME}
dataSource.portNumber=${DB_PORT}
dataSource.serverName=${DB_SERVER_NAME}
